Create a new Dockerfile for deployment
thoughtbot's heroku-haskell-stack Dockerfile hasn't been updated in 3
years[0], so use FP Complete's up-to-date Dockerfiles. As part of this
switch, remove the `stack-bootstrap` file, which was only used by the heroku-haskell-stack Docker image[1].

Additionally, switch from Heroku's deprecated container tools plugin to
the fully-supported Heroku Container Registry[2].

[0]: https://github.com/thoughtbot/docker-heroku-haskell-stack
[1]: https://github.com/thoughtbot/docker-heroku-haskell-stack/blob/a4d9d05700d977f7e552824b65390f73860332eb/Dockerfile#L26-L28
[2]: https://devcenter.heroku.com/articles/container-registry-and-runtime

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -15,16 +15,16 @@ if [ "$old_ref" = "$new_ref" ]; then
   exit 0
 fi
 
-if [ "$(uname)" = "Darwin" ]; then
-  if [ "$(docker-machine status default)" != "Running" ]; then
-      docker-machine start default
-  fi
-
-  eval "$(docker-machine env default)"
+if [ "$(docker info --format '{{.OperatingSystem}}' 2>/dev/null)" != 'Docker for Mac' ]; then
+  # Docker for Mac is not running, or we're not on a Mac.
+  # Either way, quit.
+  echo "!! Can't connect to Docker. Please start Docker for Mac."
+  exit 1
 fi
 
 heroku container:login
-heroku container:push --remote "$1"
+heroku container:push web --remote "$1"
+heroku container:release web --remote "$1"
 heroku config:set DEPLOYED_GIT_SHA="$new_ref" --remote "$1"
 
 echo "Old SHA: $old_ref"
